### PR TITLE
fix: call async methods on hass asyncio loop + add poetry for easier development

### LINKED ISSUE #80: ServiceUnavailable: after working for many months
Hi,

first of all, thank you for a great integration!

I have been using your component for many months and it was working nicely. Sometimes I faced the below issue and restarting the machine usually fixed it.
But not this time. No matter what I do - restart HA, restart machine, this error never goes away. There was no particular change that I know of. I was using version `3.21.0`.

I noticed that the permissions were root read/writable so I changed that:
```
$ ls -lah /dev/hidraw0 
crwxrwxrwx 1 root root 246, 0 Sep 20 07:57 /dev/hidraw0
```

Can you figure out what is the problem from the incoming pockets?

Thanks a lot

```
2023-09-20 08:25:32.290 DEBUG (ThreadPoolExecutor-4_1) [custom_components.jablotron100] Outcoming: 300102
2023-09-20 08:25:32.291 DEBUG (ThreadPoolExecutor-4_1) [custom_components.jablotron100] Outcoming: 300108
2023-09-20 08:25:32.291 DEBUG (ThreadPoolExecutor-4_1) [custom_components.jablotron100] Outcoming: 300109
2023-09-20 08:25:32.299 DEBUG (ThreadPoolExecutor-3_0) [custom_components.jablotron100] Incoming: d0089c68803fe0658814
2023-09-20 08:25:32.300 DEBUG (ThreadPoolExecutor-4_0) [custom_components.jablotron100] Incoming: d0089c68803fe0658814
2023-09-20 08:25:32.306 DEBUG (ThreadPoolExecutor-4_0) [custom_components.jablotron100] Incoming: 4008024a412d3130334b
2023-09-20 08:25:32.308 DEBUG (ThreadPoolExecutor-4_0) [custom_components.jablotron100] Incoming: 400c084d44363131322e30362e30
2023-09-20 08:25:32.311 DEBUG (ThreadPoolExecutor-4_0) [custom_components.jablotron100] Incoming: 4008094d443135303035
2023-09-20 08:25:32.313 DEBUG (MainThread) [custom_components.jablotron100] Central unit: JA-103K (hardware: MD6112.06.0, firmware: MD15005)
2023-09-20 08:25:32.318 DEBUG (ThreadPoolExecutor-5_1) [custom_components.jablotron100] Outcoming: 80080339393933323437
2023-09-20 08:25:32.378 DEBUG (ThreadPoolExecutor-5_0) [custom_components.jablotron100] Incoming: 801a0cffffffff0f000f002820010027ffffffffffffffffffffffff
2023-09-20 08:25:32.380 DEBUG (ThreadPoolExecutor-5_0) [custom_components.jablotron100] Incoming: d0089630843fe065a854
2023-09-20 08:25:33.914 DEBUG (ThreadPoolExecutor-5_0) [custom_components.jablotron100] Incoming: d206a42a09000000
2023-09-20 08:25:47.319 ERROR (MainThread) [custom_components.jablotron100] Service unavailable: 
Traceback (most recent call last):
  File "/config/custom_components/jablotron100/jablotron.py", line 681, in _detect_devices
    packets = reader.result(estimated_duration * 2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError
2023-09-20 08:25:47.332 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
  File "/config/custom_components/jablotron100/jablotron.py", line 681, in _detect_devices
    packets = reader.result(estimated_duration * 2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron100/__init__.py", line 30, in async_setup_entry
    await jablotron_instance.initialize()
  File "/config/custom_components/jablotron100/jablotron.py", line 290, in initialize
    await self._detect_and_create_devices_and_sections_and_pg_outputs()
  File "/config/custom_components/jablotron100/jablotron.py", line 301, in _detect_and_create_devices_and_sections_and_pg_outputs
    self._detect_devices()
  File "/config/custom_components/jablotron100/jablotron.py", line 685, in _detect_devices
    raise ServiceUnavailable
custom_components.jablotron100.errors.ServiceUnavailable

```

### PR DESCRIPTION
**Pull request by zlymeda**
Fixes #80 

I did lots of debugging, I added more debug statements to the `reader` and `writer` functions and I discovered that the stream was never closed and that my writer was stuck at sending the authorization packet.

```python
def callback(_) -> None:
	stream.close()

try:
	async_call_later(self._hass, 0.1, callback)
except Exception as ex:
	pass
```

I found a few places where we called an `async` function on a worker thread and that caused errors as the `async` function needs to be processed on a thread that owns the `loop`.

I also added poetry, as I find it easy to install it for local testing. Let me know if you don't want that.

Thank you

### CODE REVIEW

**Comment by kukulich** [comment]
We cannot remove the 1 second timeout - it wiľ break installation of other people

**Comment by zlymeda** [comment]
> We cannot remove the 1 second timeout - it wiľ break installation of other people

do you know why it is necessary?
it was not called for me for some reason, I think because of calling it in wrong thread.
so I can run it similarly as the other fixes.

I was just wondering what is the reason for that timeout.

**Comment by zlymeda** [comment]
hi @kukulich  I posted an update. however, I am not sure if it is a good idea to close a stream in the main "UI" thread
let me know what you think

**Comment by kukulich** [comment]
There was problem that without the timeout the stream was closed to early and the sent packet was not delivered to Jablotron.

**Comment by kukulich** [comment]
I think this version was used earlier but HA started to report it as problematic codde.

**Comment by zlymeda** [comment]
> I think this version was used earlier but HA started to report it as problematic codde.

ok, I will try to update it on my side and test it to see if there are issues.
I could see this being a problem only if this was run on the "UI" thread

**Comment by zlymeda** [comment]
@kukulich OK, so I know what was the problem. the `_send_packet_by_stream` is called both on the main thread as well as on the worker threads.
it is okay to do sleep and close it on the current thread if we are not on a main thread.

let me know what you think. I tested this and integration loads find, I tried arming/disarming as well as motion sensors and smoke detectors seem to be working and reporting fine.

**Comment by kukulich** [comment]
@zlymeda is it possible to test just the changes that are necessary to fix the bug?

**Comment by kukulich** [comment]
I've tested it in my environment and it looks there's no problem so I'll merge it. Thanks.

**Pull request merged**
